[project]
name = "mlflow-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagshub>=0.5.9",
    "mlflow==2.21.2",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
